CyclomaticComplexity:
  Max: 8
MethodLength:
  Max: 60
ClassLength:
  Max: 300
ClassVars:
  Enabled: false
PerceivedComplexity:
  Max: 10
AbcSize:
  Max: 120
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: false
